@startuml

title __SC2002-HMS's Class Diagram__\n

  namespace  {
    class Administrator {
    }
  }
  

  namespace  {
    class Administrator {
    }
  }
  

  namespace  {
    class Appointment {
    }
  }
  

  namespace  {
    class Appointment {
    }
  }
  

  namespace  {
    class AppointmentOutcomeRecord {
    }
  }
  

  namespace  {
    class AppointmentOutcomeRecord {
    }
  }
  

  namespace  {
    class Availability {
    }
  }
  

  namespace  {
    class Availability {
    }
  }
  

  namespace  {
    class Available {
    }
  }
  

  namespace  {
    class Available {
    }
  }
  

  namespace  {
    class CSVReader {
    }
  }
  

  namespace  {
    class CSVReader {
    }
  }
  

  namespace  {
    class Doctor {
    }
  }
  

  namespace  {
    class Doctor {
    }
  }
  

  namespace  {
    class HMS {
    }
  }
  

  namespace  {
    class HMS {
    }
  }
  

  namespace  {
    namespace MS {
      class HMS.Inventory {
      }
    }
  }
  

  namespace  {
    namespace MS {
      class HMS.Pharmacist {
      }
    }
  }
  

  namespace  {
    namespace MS {
      class HMS.Prescription {
      }
    }
  }
  

  namespace  {
    class Inventory {
    }
  }
  

  namespace  {
    class InventoryManagement {
    }
  }
  

  namespace  {
    class InventoryManagement {
    }
  }
  

  namespace  {
    class MedicalRecord {
    }
  }
  

  namespace  {
    class MedicalRecord {
    }
  }
  

  namespace  {
    class MedicineParser {
    }
  }
  

  namespace  {
    class MedicineParser {
    }
  }
  

  namespace  {
    class Patient {
    }
  }
  

  namespace  {
    class Patient {
    }
  }
  

  namespace  {
    class PatientParser {
    }
  }
  

  namespace  {
    class PatientParser {
    }
  }
  

  namespace  {
    class Pharmacist {
    }
  }
  

  namespace  {
    class Prescription {
    }
  }
  

  namespace  {
    class StaffManagement {
    }
  }
  

  namespace  {
    class StaffManagement {
    }
  }
  

  namespace  {
    class StaffParser {
    }
  }
  

  namespace  {
    class StaffParser {
    }
  }
  

  namespace  {
    abstract class User {
    }
  }
  

  namespace  {
    abstract class User {
    }
  }
  

  Administrator -up-|> User
  Administrator o-- InventoryManagement : inventoryManagement
  Administrator o-- StaffManagement : staffManagement
  Administrator -up-|> User
  Administrator o-- InventoryManagement : inventoryManagement
  Administrator o-- StaffManagement : staffManagement
  Appointment o-- Doctor : doctor
  Appointment o-- AppointmentOutcomeRecord : outcome
  Appointment o-- Patient : patient
  Appointment o-- Doctor : doctor
  Appointment o-- AppointmentOutcomeRecord : outcome
  Appointment o-- Patient : patient
  Availability o-- Doctor : doctor
  Availability o-- Doctor : doctor
  Doctor -up-|> User
  Doctor o-- Available : availableDates
  Doctor o-- Available : personalSchedule
  Doctor -up-|> User
  Doctor o-- Available : availableDates
  Doctor o-- Available : personalSchedule
  MedicineParser .up.|> CSVReader.CSVParser
  MedicineParser .up.|> CSVReader.CSVParser<Stock>
  Patient -up-|> User
  Patient o-- Available : availableDates
  Patient o-- MedicalRecord : medicalRecord
  Patient -up-|> User
  Patient o-- Available : availableDates
  Patient o-- MedicalRecord : medicalRecord
  PatientParser .up.|> CSVReader.CSVParser<Patient>
  PatientParser .up.|> CSVReader.CSVParser
  Pharmacist -up-|> User
  StaffParser .up.|> CSVReader.CSVParser
  StaffParser .up.|> CSVReader.CSVParser<User>


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
