@startuml

title __SC2002-HMS's Class Diagram__\n

  namespace  {
    namespace ontroller {
      class controller.InventoryManagement {
      }
    }
  }
  

  namespace  {
    namespace ontroller {
      class controller.InventoryManagement {
      }
    }
  }
  

  namespace  {
    namespace ontroller {
      class controller.StaffManagement {
      }
    }
  }
  

  namespace  {
    namespace ontroller {
      class controller.StaffManagement {
      }
    }
  }
  

  namespace  {
    namespace odel {
      class model.Administrator {
      }
    }
  }
  

  namespace  {
    namespace odel {
      class model.Administrator {
      }
    }
  }
  

  namespace  {
    namespace odel {
      class model.Appointment {
      }
    }
  }
  

  namespace  {
    namespace odel {
      class model.Appointment {
      }
    }
  }
  

  namespace  {
    namespace odel {
      class model.AppointmentOutcomeRecord {
      }
    }
  }
  

  namespace  {
    namespace odel {
      class model.AppointmentOutcomeRecord {
      }
    }
  }
  

  namespace  {
    namespace odel {
      class model.Availability {
      }
    }
  }
  

  namespace  {
    namespace odel {
      class model.Availability {
      }
    }
  }
  

  namespace  {
    namespace odel {
      class model.Available {
      }
    }
  }
  

  namespace  {
    namespace odel {
      class model.Available {
      }
    }
  }
  

  namespace  {
    namespace odel {
      class model.Doctor {
      }
    }
  }
  

  namespace  {
    namespace odel {
      class model.Doctor {
      }
    }
  }
  

  namespace  {
    namespace odel {
      class model.Inventory {
      }
    }
  }
  

  namespace  {
    namespace odel {
      class model.Inventory {
      }
    }
  }
  

  namespace  {
    namespace odel {
      class model.MedicalRecord {
      }
    }
  }
  

  namespace  {
    namespace odel {
      class model.MedicalRecord {
      }
    }
  }
  

  namespace  {
    namespace odel {
      class model.Patient {
      }
    }
  }
  

  namespace  {
    namespace odel {
      class model.Patient {
      }
    }
  }
  

  namespace  {
    namespace odel {
      class model.Pharmacist {
      }
    }
  }
  

  namespace  {
    namespace odel {
      class model.Pharmacist {
      }
    }
  }
  

  namespace  {
    namespace odel {
      class model.Prescription {
      }
    }
  }
  

  namespace  {
    namespace odel {
      class model.Prescription {
      }
    }
  }
  

  namespace  {
    namespace odel {
      abstract class model.User {
      }
    }
  }
  

  namespace  {
    namespace odel {
      abstract class model.User {
      }
    }
  }
  

  namespace  {
    namespace ystem {
      class system.AdministratorParser {
      }
    }
  }
  

  namespace  {
    namespace ystem {
      class system.AdministratorParser {
      }
    }
  }
  

  namespace  {
    namespace ystem {
      class system.CSVReader {
      }
    }
  }
  

  namespace  {
    namespace ystem {
      class system.CSVReader {
      }
    }
  }
  

  namespace  {
    namespace ystem {
      class system.DoctorParser {
      }
    }
  }
  

  namespace  {
    namespace ystem {
      class system.DoctorParser {
      }
    }
  }
  

  namespace  {
    namespace ystem {
      class system.HMS {
      }
    }
  }
  

  namespace  {
    namespace ystem {
      class system.HMS {
      }
    }
  }
  

  namespace  {
    namespace ystem {
      class system.InventoryParser {
      }
    }
  }
  

  namespace  {
    namespace ystem {
      class system.InventoryParser {
      }
    }
  }
  

  namespace  {
    namespace ystem {
      class system.PatientParser {
      }
    }
  }
  

  namespace  {
    namespace ystem {
      class system.PatientParser {
      }
    }
  }
  

  namespace  {
    namespace ystem {
      class system.PharmacistParser {
      }
    }
  }
  

  namespace  {
    namespace ystem {
      class system.PharmacistParser {
      }
    }
  }
  

  namespace  {
    namespace ystem {
      class system.StaffParser {
      }
    }
  }
  

  namespace  {
    namespace ystem {
      class system.StaffParser {
      }
    }
  }
  

  namespace  {
    class testing {
    }
  }
  

  namespace  {
    class testing {
    }
  }
  

  namespace  {
    namespace iew {
      class view.AppointmentOutcomeRecordDisplay {
      }
    }
  }
  

  namespace  {
    namespace iew {
      class view.AppointmentOutcomeRecordDisplay {
      }
    }
  }
  

  namespace  {
    namespace iew {
      class view.DayChecker {
      }
    }
  }
  

  namespace  {
    namespace iew {
      class view.DayChecker {
      }
    }
  }
  

  namespace  {
    namespace iew {
      interface view.Display {
      }
    }
  }
  

  namespace  {
    namespace iew {
      interface view.Display {
      }
    }
  }
  

  namespace  {
    namespace iew {
      interface view.DisplayInfo {
      }
    }
  }
  

  namespace  {
    namespace iew {
      interface view.DisplayInfo {
      }
    }
  }
  

  namespace  {
    namespace iew {
      interface view.DisplayMenu {
      }
    }
  }
  

  namespace  {
    namespace iew {
      interface view.DisplayMenu {
      }
    }
  }
  

  namespace  {
    namespace iew {
      class view.DoctorDisplayMenu {
      }
    }
  }
  

  namespace  {
    namespace iew {
      class view.DoctorDisplayMenu {
      }
    }
  }
  

  namespace  {
    namespace iew {
      class view.EmailUpdateDisplay {
      }
    }
  }
  

  namespace  {
    namespace iew {
      class view.EmailUpdateDisplay {
      }
    }
  }
  

  namespace  {
    namespace iew {
      interface view.Input {
      }
    }
  }
  

  namespace  {
    namespace iew {
      interface view.Input {
      }
    }
  }
  

  namespace  {
    namespace iew {
      class view.InputDayChoice {
      }
    }
  }
  

  namespace  {
    namespace iew {
      class view.InputDayChoice {
      }
    }
  }
  

  namespace  {
    namespace iew {
      interface view.InputInt {
      }
    }
  }
  

  namespace  {
    namespace iew {
      interface view.InputInt {
      }
    }
  }
  

  namespace  {
    namespace iew {
      class view.InputIntChoice {
      }
    }
  }
  

  namespace  {
    namespace iew {
      class view.InputIntChoice {
      }
    }
  }
  

  namespace  {
    namespace iew {
      class view.InputMonthChoice {
      }
    }
  }
  

  namespace  {
    namespace iew {
      class view.InputMonthChoice {
      }
    }
  }
  

  namespace  {
    namespace iew {
      class view.InputPrescriptionChoice {
      }
    }
  }
  

  namespace  {
    namespace iew {
      class view.InputPrescriptionChoice {
      }
    }
  }
  

  namespace  {
    namespace iew {
      interface view.InputString {
      }
    }
  }
  

  namespace  {
    namespace iew {
      interface view.InputString {
      }
    }
  }
  

  namespace  {
    namespace iew {
      class view.InputTimeChoice {
      }
    }
  }
  

  namespace  {
    namespace iew {
      class view.InputTimeChoice {
      }
    }
  }
  

  namespace  {
    namespace iew {
      class view.InventoryDisplay {
      }
    }
  }
  

  namespace  {
    namespace iew {
      class view.InventoryDisplay {
      }
    }
  }
  

  namespace  {
    namespace iew {
      class view.PatientDisplayMenu {
      }
    }
  }
  

  namespace  {
    namespace iew {
      class view.PatientDisplayMenu {
      }
    }
  }
  

  namespace  {
    namespace iew {
      class view.PharmacistDisplayMenu {
      }
    }
  }
  

  namespace  {
    namespace iew {
      class view.PharmacistDisplayMenu {
      }
    }
  }
  

  namespace  {
    namespace iew {
      class view.PrescriptionDisplay {
      }
    }
  }
  

  namespace  {
    namespace iew {
      class view.PrescriptionDisplay {
      }
    }
  }
  

  namespace  {
    namespace iew {
      class view.ReplenishmentRequestMenu {
      }
    }
  }
  

  namespace  {
    namespace iew {
      class view.ReplenishmentRequestMenu {
      }
    }
  }
  

  namespace  {
    namespace iew {
      class view.UpdatePresriptionStatusMenu {
      }
    }
  }
  

  namespace  {
    namespace iew {
      class view.UpdatePresriptionStatusMenu {
      }
    }
  }
  

  model.Administrator -up-|> model.User
  model.Administrator o-- controller.InventoryManagement : inventoryManagement
  model.Administrator o-- controller.StaffManagement : staffManagement
  model.Administrator -up-|> model.User
  model.Administrator o-- controller.InventoryManagement : inventoryManagement
  model.Administrator o-- controller.StaffManagement : staffManagement
  model.Appointment o-- model.Doctor : doctor
  model.Appointment o-- model.AppointmentOutcomeRecord : outcome
  model.Appointment o-- model.Patient : patient
  model.Appointment o-- model.Doctor : doctor
  model.Appointment o-- model.AppointmentOutcomeRecord : outcome
  model.Appointment o-- model.Patient : patient
  model.Availability o-- model.Doctor : doctor
  model.Availability o-- model.Doctor : doctor
  model.Doctor -up-|> model.User
  model.Doctor o-- model.Available : availableDates
  model.Doctor o-- model.Available : personalSchedule
  model.Doctor -up-|> model.User
  model.Doctor o-- model.Available : availableDates
  model.Doctor o-- model.Available : personalSchedule
  model.Patient -up-|> model.User
  model.Patient o-- model.Available : availableDates
  model.Patient o-- model.MedicalRecord : medicalRecord
  model.Patient -up-|> model.User
  model.Patient o-- model.Available : availableDates
  model.Patient o-- model.MedicalRecord : medicalRecord
  model.Pharmacist -up-|> model.User
  model.Pharmacist -up-|> model.User
  system.AdministratorParser .up.|> system.CSVReader.CSVParser<model.User>
  system.AdministratorParser .up.|> system.CSVReader.CSVParser
  system.DoctorParser .up.|> system.CSVReader.CSVParser<model.Doctor>
  system.DoctorParser o-- model.Available : availableDates
  system.DoctorParser .up.|> system.CSVReader.CSVParser
  system.DoctorParser o-- model.Available : availableDates
  system.InventoryParser .up.|> system.CSVReader.CSVParser<model.Inventory>
  system.InventoryParser .up.|> system.CSVReader.CSVParser
  system.PatientParser .up.|> system.CSVReader.CSVParser
  system.PatientParser o-- model.Available : availableDates
  system.PatientParser .up.|> system.CSVReader.CSVParser<model.Patient>
  system.PatientParser o-- model.Available : availableDates
  system.PharmacistParser .up.|> system.CSVReader.CSVParser<model.User>
  system.PharmacistParser o-- model.Available : availableDates
  system.PharmacistParser .up.|> system.CSVReader.CSVParser
  system.PharmacistParser o-- model.Available : availableDates
  system.StaffParser .up.|> system.CSVReader.CSVParser
  system.StaffParser o-- model.Available : availableDates
  system.StaffParser .up.|> system.CSVReader.CSVParser<model.User>
  system.StaffParser o-- model.Available : availableDates
  testing -up-|> model.User
  testing -up-|> model.User
  view.AppointmentOutcomeRecordDisplay .up.|> view.DisplayInfo
  view.AppointmentOutcomeRecordDisplay .up.|> view.DisplayInfo
  view.DoctorDisplayMenu .up.|> view.DisplayMenu
  view.DoctorDisplayMenu .up.|> view.DisplayMenu
  view.EmailUpdateDisplay .up.|> view.DisplayInfo
  view.EmailUpdateDisplay .up.|> view.DisplayInfo
  view.InputDayChoice -up-|> view.InputIntChoice
  view.InputDayChoice -up-|> view.InputIntChoice
  view.InputIntChoice .up.|> view.InputInt
  view.InputIntChoice .up.|> view.InputInt
  view.InputMonthChoice -up-|> view.InputIntChoice
  view.InputMonthChoice -up-|> view.InputIntChoice
  view.InputPrescriptionChoice -up-|> view.InputIntChoice
  view.InputPrescriptionChoice -up-|> view.InputIntChoice
  view.InputTimeChoice -up-|> view.InputIntChoice
  view.InputTimeChoice -up-|> view.InputIntChoice
  view.PatientDisplayMenu .up.|> view.DisplayMenu
  view.PatientDisplayMenu .up.|> view.DisplayMenu
  view.PharmacistDisplayMenu .up.|> view.DisplayMenu
  view.PharmacistDisplayMenu .up.|> view.DisplayMenu
  view.ReplenishmentRequestMenu .up.|> view.DisplayMenu
  view.ReplenishmentRequestMenu .up.|> view.DisplayMenu
  view.UpdatePresriptionStatusMenu .up.|> view.DisplayMenu
  view.UpdatePresriptionStatusMenu .up.|> view.DisplayMenu


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
