@startuml

title __SRC's Class Diagram__\n

  namespace  {
    class Administrator {
        - scan : Scanner
        + Administrator()
        + approveRequest()
        + displayMenu()
        + manageInventory()
        + manageStaff()
    }
  }
  

  namespace  {
    class Appointment {
        - date : String
        - status : String
        - time : String
        + Appointment()
        + getAppointmentOutcome()
        + getDate()
        + getDoctor()
        + getPatient()
        + getStatus()
        + getTime()
        + printInfo()
        + printInfoForAdmin()
        + setStatus()
        + updateAppointment()
    }
  }
  

  namespace  {
    class AppointmentOutcomeRecord {
        - consultationNotes : String
        - date : String
        - diagnoses : String
        - prescriptionList : ArrayList<Prescription>
        - treatment : String
        + AppointmentOutcomeRecord()
        + getConsultationNotes()
        + getDate()
        + getDiagnoses()
        + getPrescriptionList()
        + getTreatment()
        + printInfo()
        + setConsultationNotes()
        + setDiagnoses()
        + setPrescriptionList()
        + setTreatment()
    }
  }
  

  namespace  {
    class Availability {
        - date : String
        - status : String
        - time : String
        + Availability()
        + getDate()
        + getDoctor()
        + getStatus()
        + getTime()
        + setStatus()
    }
  }
  

  namespace  {
    class Available {
        - availableDates : ArrayList<Availability>
        - scan : Scanner
        + addAvailableDates()
        + selectAvailableSlot()
        + updateAvailableDates()
        + viewAvailableAppointmentSlots()
    }
  }
  

  namespace  {
    class CSVReader {
        + read()
    }
  }
  

  namespace  {
    interface CSVReader.CSVParser {
        {abstract} + parse()
    }
  }
  

  namespace  {
    class Doctor {
        - allAppointmentOutcomeRecords : ArrayList<AppointmentOutcomeRecord>
        - appointmentRequests : ArrayList<Appointment>
        - patientMedicalRecords : ArrayList<MedicalRecord>
        - scan : Scanner
        - upcomingAppointments : ArrayList<Appointment>
        + Doctor()
        + acceptOrDecline()
        + displayMenu()
        + incomingAppointment()
        + recordAppointmentOutcome()
        + setAvailability()
        + updatePatientMedicalRecord()
        + viewPatientMedicalRecords()
        + viewPersonalSchedule()
        + viewUpcomingAppointments()
        - updatePatientList()
    }
  }
  

  namespace  {
    class HMS {
        {static} + main()
    }
  }
  

  namespace  {
    namespace MS {
      class HMS.Inventory {
          - alertLevel : int
          - medicineName : String
          - status : String
          - stockAvailable : int
          + Inventory()
          + display()
          + getName()
          + getStatus()
          + getStock()
          + setStatus()
          + updateStock()
          - lowStockAlert()
      }
    }
  }
  

  namespace  {
    namespace MS {
      class HMS.Pharmacist {
          - allAppointmentOutcomeRecords : ArrayList<AppointmentOutcomeRecord>
          - allInventoryItems : ArrayList<Inventory>
          - scan : Scanner
          + Pharmacist()
          + displayMenu()
          + replenishmentRequest()
          + viewAppointmentOutcomeRecords()
          + viewMedicationInventory()
          - updateInventory()
          - updatePrescriptionStatus()
      }
    }
  }
  

  namespace  {
    namespace MS {
      class HMS.Prescription {
          - medicineName : String
          - status : String
          + Prescription()
          + display()
          + getName()
          + getStatus()
          + updateStatus()
      }
    }
  }
  

  namespace  {
    class InventoryManagement {
        + addStocks()
        + approveRequest()
        + manageInventory()
        + removeStocks()
        + updateAlertLine()
        + updateStocks()
    }
  }
  

  namespace  {
    class MedicalRecord {
        - bloodType : String
        - dateOfBirth : String
        - diagnosesTreatmentPrescription : ArrayList<AppointmentOutcomeRecord>
        - email : String
        - gender : String
        - name : String
        - userId : String
        + MedicalRecord()
        + getName()
        + getUserId()
        + printRecord()
        + updateRecord()
        + updateRecord()
    }
  }
  

  namespace  {
    class MedicineParser {
        + parse()
    }
  }
  

  namespace  {
    class Patient {
        - allAppointments : ArrayList<Appointment>
        - appointmentOutcomeRecords : ArrayList<AppointmentOutcomeRecord>
        - scan : Scanner
        - scheduledAppointments : ArrayList<Appointment>
        + Patient()
        + cancelAppointment()
        + displayMenu()
        + getMedicalRecord()
        + getScheduledAppointments()
        + rescheduleAppointment()
        + scheduleAppointment()
        + updateAppointmentOutcomeRecords()
        + updatePersonalInfo()
        + viewAppointmentOutcomeRecords()
        + viewMedicalRecord()
        + viewScheduledAppointments()
    }
  }
  

  namespace  {
    class PatientParser {
        + parse()
    }
  }
  

  namespace  {
    class StaffManagement {
        + addStaff()
        + displayStaff()
        + manageStaff()
        + removeStaff()
        + updateStaff()
    }
  }
  

  namespace  {
    class StaffParser {
        + parse()
    }
  }
  

  namespace  {
    abstract class User {
        - age : int
        - gender : String
        - name : String
        - password : String
        - userId : String
        + User()
        + changePassword()
        {abstract} + displayMenu()
        + getName()
        + getPassword()
        + getUserId()
    }
  }
  

  Administrator -up-|> User
  Administrator o-- InventoryManagement : inventoryManagement
  Administrator o-- StaffManagement : staffManagement
  Appointment o-- Doctor : doctor
  Appointment o-- AppointmentOutcomeRecord : outcome
  Appointment o-- Patient : patient
  Availability o-- Doctor : doctor
  CSVReader +-down- CSVReader.CSVParser
  Doctor -up-|> User
  Doctor o-- Available : availableDates
  Doctor o-- Available : personalSchedule
  MedicineParser .up.|> CSVReader.CSVParser
  Patient -up-|> User
  Patient o-- Available : availableDates
  Patient o-- MedicalRecord : medicalRecord
  PatientParser .up.|> CSVReader.CSVParser
  StaffParser .up.|> CSVReader.CSVParser


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
